### ISSUE TITLE
How to config to only check the lookbehind regexp

### ISSUE THREAD

**Issue by hongqi-lgs** [JonasBa/eslint-plugin-no-lookahead-lookbehind-regexp#2]
lookahead regexp is  now supported in almost all of the advanced browser. so how to only check lookbehind regexp.

**Comment by tommoor** [comment]
Same question, look ahead is now widely supported – but lookbehind is still unsupported in latest Safari.

**Comment by JonasBa** [comment]
Let me look at adding support for this right now. The parsing part already detects this, we should be able to just bypass the check based on a rule.

**Comment by JonasBa** [comment]
Should be solved in https://github.com/JonasBa/eslint-plugin-no-lookahead-lookbehind-regexp#4-customizing-rules, just upgrade the plugin to 0.1.0 :)
